### PR TITLE
PSBT satisfier fix

### PR DESCRIPTION
**Pull request by darosior**
A sneaky bug i found while migrating my cooked satisfier to The Official Psbt Satisfier :tm:.

### CODE REVIEW

**Review by apoelstra — DISMISSED** [review]
lol

**Comment by apoelstra** [comment]
Can you add a commit which does a patch release?

**Comment by darosior** [comment]
Done

**Review by sanket1729 — APPROVED** [review]
tACK 261d4efe4ebb452f062d015d5c6ba84cf2980dcb.

**Pull request merged**
