### PR TITLE
Derive std::hash::Hash for Descriptor et al

### PR DESCRIPTION
**Pull request by stevenroose**
Actually, I'm quite confused by this. The `Miniscript` type derives `Hash` without the `ScriptContext` trait requiring `Hash`, but when I tried for `Descriptor` it would complain about that. Is there some magic that made it work in `Miniscript`? Ideally we wouldn't require the `Hash` on `ScriptContext` there, but it doesn't hurt either.

### CODE REVIEW

**Comment by sanket1729** [comment]
utACK, looks like there are some rust 1.29 errors

**Comment by stevenroose** [comment]
I pushed some CI fixes here, if you prefer them separate, I can take them apart.

**Comment by apoelstra** [comment]
@stevenroose when we derive `Hash` for `Miniscript`, it only implements `Hash` in the case that the generic `ScriptContext` also implements `Hash`....in other words, never. Oops.

**Review by apoelstra — APPROVED** [review]
ack 8e52efbe44cb1c6be2516818bd283a856ba6607b

**Comment by apoelstra** [comment]
(To clarify my above comment -- this PR fixes the issue by putting a `std::Hash` requirement on the `ScriptContext` trait.)

**Pull request merged**
