### PR TITLE
Release 8.0.0

### PR DESCRIPTION
**Pull request by sanket1729**
Draft release PR. Still blocked on reviews of

1) #418 
2) #450 
3) #461

### CODE REVIEW

**Comment by sanket1729** [comment]
I have also added the 8.0.0 milestone to the PRs that are blocking

**Comment by darosior** [comment]
What do you think of sneaking in https://github.com/rust-bitcoin/rust-miniscript/pull/470 too? It breaks some APIs hence needs a major version bump.
The BIP is still only a PR to the bips repository, but the idea has now got an [implementation](https://github.com/bitcoin/bitcoin/pull/22838) in [various](https://github.com/bitcoin/bitcoin/issues/17190#issuecomment-968071037) [softwares](https://github.com/Coldcard/firmware/pull/145) and the BIP itself received [decent feedback](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2022-July/020791.html). I'd be in favour of a [small tweak to it](https://github.com/bitcoin/bips/pull/1354#discussion_r985316649) but i can live without.

**Comment by apoelstra** [comment]
I wouldn't mind getting #470 in. Yes, it's only a draft and may change, but we've got a bunch of other stuff in this library that's also subject to change (and a lot of stuff which is not specced out very well, or at all).

We definitely did 1.0 years too early here :)

**Comment by sanket1729** [comment]
@darosior, I think #470 would take some time to get in :( and we would like to cut a release because it's been a long time, but don't have a rust-bitcoin 0.29 release.

**Review by apoelstra — APPROVED** [review]
ACK 3f451db9a8b00b88ca8b7b6fe0334707efe8d88c

**Pull request merged**
