### PR TITLE
.gitignore:*.DS_Store

### PR DESCRIPTION
**Pull request by RandyMcMillan**

### CODE REVIEW

**Comment by RandyMcMillan** [comment]
related:
https://github.com/rust-bitcoin/rust-miniscript/pull/626

**Review by tcharding — APPROVED** [review]
ACK 7c98132ad11651e892fa8a8a1c2f925b7537e474

Although this will conflict with #626, might as well roll that one into this one I'd say.

**Review by apoelstra — APPROVED** [review]
ACK 7c98132ad11651e892fa8a8a1c2f925b7537e474

**Comment by RandyMcMillan** [comment]
of coarse it can be done from a global .gitignore :)
I guess the approach is to have the repo autonomous.

**Pull request merged**
