### PR TITLE
Enable edition 2018

### PR DESCRIPTION
**Pull request by tcharding**
Update the MSRV to Rust 1.41.1 and enable edition 2018.

I'm not sure how we want to merge these MSRV PRs across the stack but here is the `rust-miniscript` one.

Discussion: https://github.com/rust-bitcoin/rust-bitcoin/issues/510#issuecomment-881686342

### CODE REVIEW

**Comment by sanket1729** [comment]
I think the MSRV change can go in any order. I would like to get an external contributor #339 PR in first before we address this. That already has ACK from me, but would also like Andrew's ACK(it's a somewhat big change) before we proceed with it.

**Review by apoelstra — APPROVED** [review]
ACK 900ae8ae839cd8c66e8b54005667318b8d129c61

**Review by sanket1729 — APPROVED** [review]
ACK 9bbef6744844549a9232f8276efd9ff40d70025a

**Comment by sanket1729** [comment]
Sorry, this now conflicts after we got #339 in

**Comment by tcharding** [comment]
Changes in force push:
- Rebase on master
- Fix commit: `08bce7a Update to use edition 2018` as needed

**Comment by tcharding** [comment]
FTR please do not worry about merge conflicts caused by this PR in relation to any of my other PRs, I'm fine to rebase.

**Review by sanket1729 — APPROVED** [review]
ACK c60bf1e1134acfe3cc60b46f80651672d2e70771. redid the entire process to match the diff.

**Comment by tcharding** [comment]
BOOM! The first edition 2018 PR to be merged across the stack, way to go!

**Pull request merged**
