### PR TITLE
Do some random trivial fixes

### PR DESCRIPTION
**Pull request by tcharding**
All changes explained in their respective patch.

### CODE REVIEW

**Comment by apoelstra** [comment]
Failing rustfmt check.

**Comment by tcharding** [comment]
Rebased on master and fixed formatting issues.

**Review by apoelstra — APPROVED** [review]
ACK 40672382100492be6418d0ae5810fa1eeda79d7c

**Review by sanket1729 — APPROVED** [review]
ACK c3c508eabbaa17adf3d9a180b298a9c7543316a8

**Pull request merged**
