### PR TITLE
Add default impl for `Miniscript::num_der_paths`

### PR DESCRIPTION
**Pull request by tcharding**
The trait method `MiniscriptKey::num_der_paths` often returns 0, lets just make this the default.

### CODE REVIEW

**Review by apoelstra — APPROVED** [review]
ACK a322217af2b0f89246607373873b4911b7aedb26

**Review by apoelstra — APPROVED** [review]
ACK a322217af2b0f89246607373873b4911b7aedb26

**Review by apoelstra — APPROVED** [review]
ACK a322217af2b0f89246607373873b4911b7aedb26

**Comment by apoelstra** [comment]
Lol fucking github.

**Comment by tcharding** [comment]
This PR should not be doing any logic changes, why is fuzzing breaking?

**Comment by tcharding** [comment]
Changed the last patches hash just to kick CI, no changes.

**Review by apoelstra — APPROVED** [review]
ACK 88f7f5bb4fa1326a972f76150a858addf03a93a5

**Pull request merged**
