### PR TITLE
Bitcoin 0.28.0-rc.2

### PR DESCRIPTION
**Pull request by dr-orlovsky**
This is a draft API adopting new version of rust-bitcoin 0.28.0-rc.2

### CODE REVIEW

**Comment by sanket1729** [comment]
Note that this would need to be a single commit to make sure all commits compile and test. Unfortunately, there is no clean way to have atomic commits here. 

What I typically tend to do in these cases is to have separate branches with 2 PRs, one with atomic commits and one with a single commit. And then locally check that the diff between the two is null. This is not required for this case because the diff is small and I can review it in single commit.

**Comment by dr-orlovsky** [comment]
@sanket1729 working on update

**Comment by sanket1729** [comment]
@dr-orlovsky: One other thing that needs to be fixed here: https://github.com/rust-bitcoin/rust-miniscript/blob/1f9affc43723a0669ba90cfcca83710753e032df/src/psbt/finalizer.rs#L119 Should return `&bitcoin::TxOut` instead of `bitcoin::Txout`. 

Also, the commit message should be 0.28.0-rc.2 instead of 0.27.0-rc.2.

**Comment by dr-orlovsky** [comment]
@sanket1729 will fix both of the issues once bitcoin gets released and will do a final update to use released version

**Comment by apoelstra** [comment]
Ok, rust-bitcoin rc2 is out

**Comment by dr-orlovsky** [comment]
Updating this one

**Comment by dr-orlovsky** [comment]
@apoelstra @sanket1729 ready for the review, CI is fixed

**Review by sanket1729 — APPROVED** [review]
tACK 08ed922ec9873eb363a4a95880a08a2e23658209. The commit message still says 0.27, but I can live with it

**Comment by dr-orlovsky** [comment]
ouh, sorry for forgetting about that message :(

**Comment by sanket1729** [comment]
Tagged and published.

**Pull request merged**
