### PR TITLE
README.md: update examples link

### PR DESCRIPTION
**Pull request by RandyMcMillan**

### CODE REVIEW

**Review by tcharding — APPROVED** [review]
ACK aa33bd4529de5de93d7ee6e34a8b358314d10a6e

**Review by apoelstra — APPROVED** [review]
ACK aa33bd4529de5de93d7ee6e34a8b358314d10a6e

**Comment by apoelstra** [comment]
All the CI failures are due to the nightly compiler triggering new "unused import" lints. Fixed by #627 .

**Comment by apoelstra** [comment]
Heads up that you will get notifications @RandyMcMillan related to this merge, because the name you use for git commits contains your Github username prefixed with an @. If this is a problem for you I suggest changing your name in your .gitconfig to drop the @.

**Pull request merged**
