### PR TITLE
Move dummy types to submodule

### PR DESCRIPTION
**Pull request by tcharding**
Clippy warns about the dummy types, in an effort to clear all clippy warnings do:

- Create a submodule `dummy` and move all the dummy key types there (refactor/clean up).
- Manually implement `PartialEq` and `Eq` for all the dummy types.

### CODE REVIEW

**Comment by apoelstra** [comment]
We could rename these as well to drop `Dummy` from the name if we have a module called `dummy`.

As for the clippy thing, SGTM, though I think it's being stupid.

**Comment by tcharding** [comment]
> As for the clippy thing, SGTM, though I think it's being stupid.

Its acting like a dummy - (couldn't help myself)

**Comment by tcharding** [comment]
Changes in force push:
- Removed the `Dummy` prefix and used `dummy::Foo` where necessary
- Added an additional patch in the middle of the series to keep the diffs clean

**Comment by tcharding** [comment]
... and run the formatter

**Review by apoelstra — APPROVED** [review]
ACK 6c6b9fc424f42357b7e58fa883418576bf72f357

**Comment by tcharding** [comment]
Please see #508 before merging this, perhaps we just want to remove the dummy types altogether and use `String`?

**Comment by sanket1729** [comment]
@tcharding, agreed. It is best to remove the dummy keys altogether

**Comment by tcharding** [comment]
Unneeded since #508 merged.

**Pull request closed without merging**
