### PR TITLE
10.x backport

### PR DESCRIPTION
**Pull request by sanket1729**

### CODE REVIEW

**Comment by sanket1729** [comment]
@apoelstra. We had lots of CI fixes particularly for fuzz fixes, strict dead code errors. Is it possible to locally test the package and cut a release?

**Comment by apoelstra** [comment]
Yep, I will locally test things.

**Comment by apoelstra** [comment]
The MSRV on this old version is 1.41.1. Your use of the `matches!` macro breaks it. Can you change the unit test?

**Comment by sanket1729** [comment]
@apoelstra changed this. Can you try testing again

**Review by apoelstra — APPROVED** [review]
ACK a4576ae70d39e8601c73330ac718216f44db63ec

**Comment by apoelstra** [comment]
I think it's good now. The CI setup on this old version is pretty weird in a few ways (different MSRV for std vs nostd, `unstable` feature that requires nightly) so I am not 100% certain. But after reading the diff and doing some spot-checks and running my local CI on it and determining that failures are "expected", I think we're good to go. Will merge and release.

**Comment by apoelstra** [comment]
Tagged and published.

**Pull request merged**
