### PR TITLE
CI: Lint the crate and examples

### PR DESCRIPTION
**Pull request by tcharding**
We are not currently running the linter in CI, do so.

### CODE REVIEW

**Comment by apoelstra** [comment]
Will `$clippy --all-targets` get the same effect?

I think we should try running
```
clippy --all-features --all-targets
clippy --all-targets
clippy --no-default-features --all-targets # maybe with --features=no-std if we require that here
```

Which I *think* will cover the examples (though let me check..) and then gets us a bit of feature-matrix coverage as well.

**Comment by apoelstra** [comment]
Yeah, confirmed that --all-targets will flag `let x = u8::from(10u8)` in an example program.

**Comment by tcharding** [comment]
Interesting, then we (I) got it wrong in `rust-bitcoin` - I thought I had checked this before.

IIUC running the linter with different feature flags only adds checking unused imports when features are turned off, and while its nice to have these correct I'm not sure its worth bothering contributors with failing CI runs for it?

**Comment by tcharding** [comment]
I was wrong we get real errors with `cargo +nightly clippy --no-default-features --features=no-std --all-targets -- -D warnings` that we don't get with `--all-features` - WIN.

Here is an example (there are a few more)
```bash
error: this expression creates a reference which is immediately dereferenced by the compiler
   --> src/lib.rs:757:37
    |
757 |             fn deref(&self) -> &T { &self.lock.deref() }
    |                                     ^^^^^^^^^^^^^^^^^^ help: change this to: `self.lock.deref()`
```

**Comment by tcharding** [comment]
Now includes two clippy fixes up front and uses the three feature gate combinations suggested.

**Review by apoelstra — APPROVED** [review]
ACK a410c06b3f1a452f4fa1095558d8f0618ca371af

**Pull request merged**
