### PR TITLE
Return Weight type for max_weight_to_satisfy methods

### PR DESCRIPTION
**Pull request by yancyribbens**
Return Weight type for max_weight_to_satisfy methods.

### CODE REVIEW

**Comment by yancyribbens** [comment]
I'm not sure if there should be a more specific error added or if there is a better one to use then the general one I picked here.

**Comment by apoelstra** [comment]
> I'm not sure if there should be a more specific error added or if there is a better one to use then the general one I picked here.

Fine to use the general one for now. I have an ambitious PR in the works that will try to add span information etc to errors so any "extra" work you do now will just get overwritten when I finish that.

**Comment by yancyribbens** [comment]
Rebased.

**Comment by apoelstra** [comment]
You need to run `cargo +nightly fmt` in this repo.

**Comment by yancyribbens** [comment]
> You need to run cargo +nightly fmt in this repo.

Thanks, done.

**Comment by apoelstra** [comment]
Now this appears to be based on the tip of #661 rather than on master.

**Comment by yancyribbens** [comment]
> Now this appears to be based on the tip of https://github.com/rust-bitcoin/rust-miniscript/pull/661 rather than on master.

Now sure how I managed that.  I'm now showing 4aaedf is now the previous commit.

**Review by apoelstra — APPROVED** [review]
ACK 7c5f3dc5b54373c12cad430d356f29bce33e9dc4

**Pull request merged**
