### PR TITLE
Add weight to max satisfaction weight

### PR DESCRIPTION
**Pull request by yancyribbens**
Return Weight type for max_satisfaction_weight methods.

### CODE REVIEW

**Comment by apoelstra** [comment]
This builds on #664 and has the same issue with commit structure.

**Comment by yancyribbens** [comment]
> This builds on https://github.com/rust-bitcoin/rust-miniscript/pull/664 and has the same issue with commit structure.

Oops, Rebase should be fixed now.

**Comment by yancyribbens** [comment]
Looks like `max_satisfaction_weight` is deprecated, maybe it's not worth changing these.

**Comment by apoelstra** [comment]
Ah, yeah, I think we should leave the deprecated methods alone. (Let's keep them in another release cycle though, since we're re-breaking the new methods..)

**Comment by yancyribbens** [comment]
max_satisfaction_weight methods are depreciated.

**Pull request closed without merging**
