### PR TITLE
Backport recursion fixes to 8.x

### PR DESCRIPTION
**Pull request by apoelstra**
I think this is the last of the rust-miniscript versions in common use.

### CODE REVIEW

**Comment by tcharding** [comment]
Is this needed still mate, want me to pick it up for you?

**Comment by apoelstra** [comment]
Yes, it's still needed. But no, I need another maintainer to merge it.

**Comment by tcharding** [comment]
No sweat.

**Comment by sanket1729** [comment]
Sorry, this skipped past me. Looking at it now

**Review by sanket1729 — APPROVED** [review]
utACK d87166547c1781191d305db139cdf2259676a8f2

**Comment by sanket1729** [comment]
Tagged and pusblished.

**Pull request merged**
