### PR TITLE
Implement From<Foo> for Descriptor<Pk> using macro

### PR DESCRIPTION
**Pull request by tcharding**
Add a macro and remove all the individual from impls.

Refactor only, no logic changes.

### CODE REVIEW

**Comment by apoelstra** [comment]
I wish there was a way that you could expand macros prior to committing them. So we could have a CI job that checked that all the code was actually produced from macros, but when reading it, you could read the expanded versions.

In C you can kinda do this by running `cpp` directly.

In Rust I guess we could also use `cpp` but that's maybe too evil :).

But basically, I like the guaranteed consistency and ease of writing macros but I really think they harm readability.

**Comment by tcharding** [comment]
> but I really think they harm readability

The first Rust job I had they barred me from writing macros because of this.

Perhaps we can find a middle ground, if the macro was called in a form more like what the code looks like it would be easier to read. It may even be easier to read because it reduces the noise.

Something like this?
```rust
// Implements From<error::Bar> for GeneralError converting to `GeneralError::Bar(error::Bar)`
impl_from_for_error_type!(error::Bar, GeneralError::Bar);
```

**Comment by apoelstra** [comment]
Can you use `for` instead of `is`? Or does Rust prevent this?

**Comment by tcharding** [comment]
We can put anything we want in there I believe, I did not code the actual macro up though. (I also had `for` at one stage when editing the original post)

**Comment by tcharding** [comment]
oh that's right, I removed `for` because its a bit weird to have for and then include the variant name.

**Comment by apoelstra** [comment]
Ah, I see. So even in your hypotheticals I misread what was going on ... I think the explicit code is probably better than anything we've got here.

One thing we could experiment with is adding `#[from]` the way that `thiserror` does. We've shied away from syntax extensions in the past but possibly this one is easy to do. Unsure. It would probably depend on `quote` which we've had MSRV trouble with in the past.

**Comment by tcharding** [comment]
I"ll leave this for now.

**Pull request closed without merging**
