### PR TITLE
Upgrade bech32 dependency

### PR DESCRIPTION
**Pull request by tcharding**
Upgrade to the newest release of the `bech32` crate.

### CODE REVIEW

**Comment by tcharding** [comment]
By "needs reviewing by a cryptographer" I meant you obviously @apoelstra :)

**Comment by apoelstra** [comment]
The length is actually 32767.

This code is very interesting in that correcting it requires working in a degree-3 extension of the base field. It'll be a good test case for our error correcting logic.

**Comment by tcharding** [comment]
> It'll be a good test case for our error correcting logic.

I read this first thing this an hour or so ago and didn't understand, you mean our "soon-to-be-implemented error correcting logic", right?

**Comment by tcharding** [comment]
Do we want a comment on the code length magic numbers (1023 and 32767)? I for one can't remember where they come. Can you either tell me again or just give what ever tip you can off the top of your head for me to research a code comment.

**Comment by apoelstra** [comment]
> I read this an hour or so ago and didn't understand, you mean our soon-to-be-implemented error correcting logic, right?

Yes.

>Do we want a comment on the code length magic numbers (1023 and 32767)? I for one can't remember where they come. Can you either tell me again or just give what ever tip you can off the top of your head for me to research a code comment.

They come from the mathematical properties of the error correcting code. Specifically it is the lcm of the order of the roots of the generating polynomial. I don't think there's a simple reason "why" that we could comment. It's kinda annoying to compute this value directly from the other code parameters. In this case I found it in a code comment block in src/script/descriptor.cpp in Bitcoin Core (and it was not labelled as "the length of the code", it was labelled as the order of a particular field element whose powers form the roots of the polynomial).

**Comment by tcharding** [comment]
How about just "This value calculable from the mathematical properties of the error correcting code."

**Comment by apoelstra** [comment]
I think that's a little misleading, since the value is a design parameter of the code. The mathematical properties come from the length (among other things), rather than the other way around.

**Comment by tcharding** [comment]
How about (can you confirm I got lcm right?)
```rust
/// The Least Common Multiple (lcm) of the order of the roots of the generating polynomial (or if you don't understand that, a property of the error correcting code).
```

**Comment by apoelstra** [comment]
This is correct, but I think it's way too technical for user-facing docs. What this parameter actually means is the maximum length of a string that can be error-corrected.

**Comment by tcharding** [comment]
Ugh, well that is clearly the doc we want: "The maximum length of a string that can be error-corrected"

We got there in the end, you math nerds, I don't know :)

**Comment by apoelstra** [comment]
Lol, well, I thought you were asking how I got the specific constant 32767, not about what the constant meant in the abstract.

**Comment by tcharding** [comment]
Ha! I did want to know that but "I grepped Core for it" answered that for me. I do enjoy the full technical description but when I have to start looking up acronyms I know its got too deep, and basically anytime I read polynomial my eyes glaze over just a little bit :) I should have done more math at uni.

**Comment by apoelstra** [comment]
BTW this is written in the docs: https://docs.rs/bech32/latest/bech32/trait.Checksum.html#associatedconstant.CODE_LENGTH

In any case, to do error correction I will need to implement a bunch more algebra that will hopefully clarify/sanity-check these values so we don't need to go digging around for them (we can just guess-and-check, or maybe I'll have code that can compute them for us).

**Comment by tcharding** [comment]
> BTW this is written in the docs:

OMG, I literally laughed out loud at my initiating that whole conversation without reading that doc - EPIC FAIL.

**Review by sanket1729 — APPROVED** [review]
ACK 6bd6301641851d3bf55ad35ee88c890d21836638

**Pull request merged**
