### PR TITLE
Fix panic while decoding large Miniscripts from Script

### PR DESCRIPTION
**Pull request by sanket1729**
Use private module to guard all constructors.

### CODE REVIEW

**Comment by apoelstra** [comment]
The new lockfiles don't work with MSRV.

**Comment by sanket1729** [comment]
@apoelstra this is ready for review.

**Comment by apoelstra** [comment]
The new lockfile updates `cc` to 1.1.6  which still does not work  with MSRV.

Ok if I force-push to this PR to try to fix the lockfiles?

**Comment by sanket1729** [comment]
@apoelstra I just tested it again with 1.56.1 and it works. 

image

**Comment by apoelstra** [comment]
Re "CI happy means we're good", see #719 -- we are actually testing only with Cargo-minimal.lock, not Cargo-recent.lock (which is broken).

Furthermore, this lockfile commit makes several unnecessary changes and because it's in a separate commit from the one that changes Cargo.toml, also means that I cannot locally test every  commit of this PR.

**Review by apoelstra — COMMENTED** [review]
Successfully ran local tests on 192c499232fe70f1a79433746223dcb91443e816.

**Review by apoelstra — APPROVED** [review]
ACK 192c499232fe70f1a79433746223dcb91443e816 successfully ran local tests

**Comment by apoelstra** [comment]
Tagged and published.

**Pull request merged**
