### PR TITLE
feat: actually check push data bytes

### PR DESCRIPTION
**Pull request by ChrisCho-H**
Miniscript witness item can be maximum 72 bytes(except length prefix), but it only throws error when it's >= 4294967296 bytes as only dependant on `PushBytesError` from bitcoin crate.  I've changed the logic to check the maximum length internally so that actual check can be done.

### CODE REVIEW

**Comment by apoelstra** [comment]
Oh, of course, the script itself could be too large! Ok concept ACK.

**Comment by apoelstra** [comment]
....which I think is also what's triggering your new tighter `expect` in `witness_to_scriptsig`. Interesting. I think this is an existing panicking bug in rust-miniscript. (Though kinda an academic one since to trigger it in our existing code you need to construct a Miniscript which encodes to more than 4Gb.) (But upstream we are considering tightening this to 32M to match Bitcoin consensus rules, and in that case we need to fix this!!)

**Comment by ChrisCho-H** [comment]
While it's true that it's impossible to hit this error in descriptor as `satisfy` called before, it's possible to hit in miniscript like `miniscript::Legacy::check_witness(witness)`. My trigger is actually just error message of `All pushes in miniscript are < 73 bytes`. It seems weird not to check maximum witness bytes with such error message.

**Comment by ChrisCho-H** [comment]
I've added the logic to check the size of redeem script and other push separately https://github.com/rust-bitcoin/rust-miniscript/pull/743/commits/9dbaad3bfd89508a388222ba9d84b7c5c3c93fac.

**Comment by apoelstra** [comment]
I would suggest squashing these two commits because they have substantial overlap in the code that they change.

Secondly, I'm struggling to understand the point of calling `map_err` and `and_then` on something we're just going to unwrap.

My suggestion, if you want to make the assertion more precise, would be to add a `debug_assert` above the push line, then change the expect message to just say "checked above".

Your method of checking whether we are on the last push is also pretty inefficient. One better way to do this is to add `.enumerate()` to the iterator and then compare the index to `witness.len() - 1`.

**Comment by apoelstra** [comment]
It can also be a real `assert` if you want. No need to `debug_assert`.

**Comment by ChrisCho-H** [comment]
Thanks for great review! I've fixed following your suggestion.

**Comment by apoelstra** [comment]
324b33d08f86c1cc99c15d740f0cbbda03804152 is looking great!

But now it doesn't look like `witness_to_scriptsig` actually returns an error anywhere :).

Could this PR be reduced to just adding the new assertions and not changing the signature of `witness_to_scriptsig` at all?

**Comment by ChrisCho-H** [comment]
You are right. No need to change the original signature. Reduced down by https://github.com/rust-bitcoin/rust-miniscript/pull/743/commits/e2e9281fcfe634d003405a7b5f6b4e63abcf1eda!

**Review by apoelstra — APPROVED** [review]
ACK e2e9281fcfe634d003405a7b5f6b4e63abcf1eda successfully ran local tests; thanks for iterating!

**Pull request merged**
