### PR TITLE
hexify for better error message

### PR DESCRIPTION
**Pull request by Harshil-Jani**
This PR hexifies the Error implementation as requested in TODO. Let me know if this works and then I can remove the "TODO : Hexify this " Comment from there. 

Signed-off-by: Harshil Jani <harshiljani2002@gmail.com>

### CODE REVIEW

**Comment by apoelstra** [comment]
concept ACK for sure. But definitely nack this particular implementation :) it allocates a string for every character and then a new one.

You can use https://docs.rs/bitcoin_hashes/latest/bitcoin_hashes/hex/fn.format_hex.html to do it without allocations. `bitcoin_hashes` is available in this crate under the path `bitcoin::hashes`.

**Comment by Harshil-Jani** [comment]
Got it. Thanks for helping @apoelstra

**Comment by apoelstra** [comment]
You shouldn't need to explicitly add a `bitcoin_hashes` dependency. Just use `bitcoin::hashes`.

**Comment by Harshil-Jani** [comment]
> Thanks for the iterations! This looks great now.
> 
> Can you squash all 3 commits into one?

Squashed.

**Comment by apoelstra** [comment]
@Harshil-Jani thanks! But now that the code is all in one place I see that you're using `format_hex` wrong. It does not return a hex-formatted object. It actually does the hex-encoding.

To accomplish what you want, the code you need is

```rust
write!(f, "invalid push ")?;
bitcoin::hashes::hex::format_hex(push, f)
```

**Review by apoelstra — APPROVED** [review]
ACK a0b001b65c10551d3dc5f816affe04df51542678

**Pull request merged**
