### PR TITLE
cleanup examples

### PR DESCRIPTION
**Pull request by tcharding**
Nothing too crazy here, just a few cleanups to the `examples` directory. Note though that commit `122be5d Move bip-174 test out of examples and into tests` moves a file out of `examples` and into a new `tests` directory.

### CODE REVIEW

**Review by sanket1729 — DISMISSED** [review]
ACK 288a6f1efe257cd45876e580671f0cb6b430959d

**Review by apoelstra — DISMISSED** [review]
ACK 288a6f1efe257cd45876e580671f0cb6b430959d

**Review by apoelstra — DISMISSED** [review]
ACK 288a6f1efe257cd45876e580671f0cb6b430959d

**Comment by tcharding** [comment]
Not sure what's going on here, I haven't touched this PR all day and there are multiple "The merge-base changed after approval." - I don't know what they are?

**Pull request merged**
