### PR TITLE
Debug ms attributes test

### PR DESCRIPTION
**Pull request by tcharding**
Try to do issue: https://github.com/rust-bitcoin/rust-miniscript/issues/347

First patch is preparation, adds a macro so each of the test vectors is checked in a separate test so we can debug.

We use the test vectors from Sipa's `miniscript/bitcoin/test/miniscript_test.cpp`. Two new vectors seem to have been added, patch 2 adds those here (they both pass).

Two of the vectors we have have different values for `ops` (also one of ours uses `nd:and_v` instead of `d:and_v`, however I do not know the implications of this), patch 2 adds the original ones as well (both fail).

With this patch set applied we have:
```
failures:
    miniscript::tests::check_attributes_15a 
    miniscript::tests::check_attributes_16 
    miniscript::tests::check_attributes_16a
    miniscript::tests::check_attributes_26
    miniscript::tests::check_attributes_27
    miniscript::tests::check_attributes_7
```

I don't have any idea how to proceed. If anyone has any suggestions I can follow them. Thanks

### CODE REVIEW

**Comment by sanket1729** [comment]
I will look into this later, but I just looked at 16a for now. This relates to calculations about malleable scripts. The c++ code outputs incorrect values for malleable scripts. 

There may be other reasons why there is a discrepancy in other cases and we should resolve this. I would suspect this again relates to the calculation when scripts are malleable.

**Comment by tcharding** [comment]
Thanks for looking @sanket1729.

**Comment by sanket1729** [comment]
Based on some discussion here: https://github.com/bitcoin/bitcoin/pull/24147#discussion_r877531692, we should only care for these values if the scripts are non-malleable. 

We should either 
1) Keep our separate tests
2) Or only test these values for non-malleable vectors.

**Comment by sanket1729** [comment]
In the future, if you need any assistance with a PR, feel free to tag me. I typically ignore the PRs in the marked draft.

**Pull request closed without merging**
