### PR TITLE
Backport 11.x of #704 

### PR DESCRIPTION
**Pull request by sanket1729**

### CODE REVIEW

**Comment by apoelstra** [comment]
Can you change the CHANGELOG to drop the thing about `LoggerAssetProvider` because I don't think that's true of the backports.

**Comment by sanket1729** [comment]
@apoelstra done

**Comment by sanket1729** [comment]
@apoelstra this is still unreleased.

**Review by apoelstra — APPROVED** [review]
ACK fd823e8ab3302b180673f1893d524d44fb0c54f2

**Comment by apoelstra** [comment]
Yep, sorry -- was hacking on my local CI to get it to work with 11.x -- but I was able to succeed, which is great. We have far better QA now on our backports than we used to. And after #682 I think that going forward, actual github CI should work for 12.x forever.

Can we do a backport to 9.x? Then we should be done as far as we intend to go.

**Comment by sanket1729** [comment]
> Can we do a backport to 9.x? 

On it. Will do in an hour or so

**Comment by apoelstra** [comment]
Tagged and published.

**Pull request merged**
