### PR TITLE
Remove hashbrown dependency

### PR DESCRIPTION
**Pull request by tcharding**
We can use `BTreeSet` instead of `HashSet` and `BTreeMap` instead of `HashMap` to remove the `hashbrown` dependency.

### CODE REVIEW

**Comment by tcharding** [comment]
Bother, will try to fix tomorrow.

**Comment by tcharding** [comment]
Putting on ice until https://github.com/rust-bitcoin/rust-miniscript/pull/569 merges so I don't have to work out the pinning.

**Comment by apoelstra** [comment]
Looking good. The CI failure suggests that this is simply incomplete.

**Comment by apoelstra** [comment]
concept ACK. I actually think the duplicated code is short enough that we could just duplicate it rather than using a macro. Unsure.

**Comment by tcharding** [comment]
So the readability thing is definitely real. On the other hand, and what I tried to assist with the comment 
```
// You can ignore the complexity of this and similar macros below, all they do is implement
// `Satisfier` on both `BTreeMap` and `HashMap` feature guarding the `HashMap` impl on "std"
// feature.
```

is that there is a trade off between the readability of the macro and the readability of the duplicate code. One thing I'm struggling with, as a newcomer to the miniscript codebase, is what code is duplicate and what code is slightly different. There is so much duplicate code that my eyes skim over things thinking they are duplicate and missing the details. I've attempted refactorings only to find that I missed some difference - perhaps its just me but the code duplication seems to make me more lazy at reading.

**Comment by tcharding** [comment]
Would putting this on top of each macro help?
```
/// Implements `Satisfier<Pk> for $map<(Pk, TapLeafHash), taproot::Signature>`.
```

**Comment by apoelstra** [comment]
Ok, this makes sense. And it is true that this library has a ton of duplicate code, some of which is almost-duplicate, and some of which should be duplicate but isn't.

Maybe if we made the macro contents look like `impl Satisfier<Pk> for BTreeMap<(Pk, TapLeafHash), taproot::Signature>;` so it's obvious what the code "should" be doing, that'd be fine with me.

**Comment by tcharding** [comment]
Oh that is kinda nice, hows this?
```rust
macro_rules! impl_satisfier_for_map_key_hash_to_taproot_sig {
    ($(#[cfg($attr:meta)])* impl Satisfier<Pk> for $map:ident<$key:ty, $val:ty>) => {
        impl<Pk: MiniscriptKey + ToPublicKey> Satisfier<Pk> for $map<$key, $val>
        {
            fn lookup_tap_leaf_script_sig(
                &self,
                key: &Pk,
                h: &TapLeafHash,
            ) -> Option<bitcoin::taproot::Signature> {
                // Unfortunately, there is no way to get a &(a, b) from &a and &b without allocating
                // If we change the signature the of lookup_tap_leaf_script_sig to accept a tuple. We would
                // face the same problem while satisfying PkK.
                // We use this signature to optimize for the psbt common use case.
                self.get(&(key.clone(), *h)).copied()
            }
        }
        
    };
}
impl_satisfier_for_map_key_hash_to_taproot_sig! {
    impl Satisfier<Pk> for BTreeMap<(Pk, TapLeafHash), bitcoin::taproot::Signature>
}
impl_satisfier_for_map_key_hash_to_taproot_sig! {
    #[cfg(feature = "std")]
    impl Satisfier<Pk> for HashMap<(Pk, TapLeafHash), bitcoin::taproot::Signature>
}
```

**Comment by apoelstra** [comment]
Yeah, that looks great to me! This way when you're looking for impls you can still find it via grep, and once you arrive at the macro call, the actual invocation is nearby and almost entirely quoted code.

**Comment by tcharding** [comment]
Cool, I'll hack it up.

**Comment by sanket1729** [comment]
concept ACK. I like the current code, but I don't think we need the pinning commit anymore

**Comment by tcharding** [comment]
I forgot I'd only done one of the macros with the new style. All done now, and squashed into a single commit although this has made the diff a bit hard to view. I can split it all back up if needed.

**Comment by apoelstra** [comment]
The CI failure looks legit (and annoying :))

**Comment by tcharding** [comment]
The problem was I forgot to add the passed in attribute inside the macro call.

**Comment by apoelstra** [comment]
The first commit doesn't compile with `cargo test --no-default-features --features no-std` anymore (and I suspect the latter commit only compiles because `HashMap` is no longer used).

**Comment by tcharding** [comment]
My bad, will investigate. Thanks

**Comment by tcharding** [comment]
Ok, there offender turned out to be one little usage of `HashMap` in a unit test. The PR is now broken up into very small digestible chunks.

**Comment by apoelstra** [comment]
In 986ed867ec3d07f874455e4a80b4c883c6b74b0d

```
cargo test --no-default-features --features='no-std compiler'
```
fails

**Comment by tcharding** [comment]
Thanks, feels a bit like you are my CI again.

**Review by apoelstra — APPROVED** [review]
ACK 49fd7b9ad80064de42b2ff2ca63fe750b609d478

**Pull request merged**
