### PR TITLE
Fix TapTree depth check bug

### PR DESCRIPTION
**Pull request by sanket1729**
As spotted in #317

### CODE REVIEW

**Comment by SarcasticNastik** [comment]
tACK aeebccd
I'm actually surprised we missed this out :p. Thanks for correcting it!

**Review by apoelstra — DISMISSED** [review]
ACK aeebccdeb1dec46f43825fa1e3cd734054067d14

**Comment by sanket1729** [comment]
Rebased after #426  was merged

**Review by apoelstra — APPROVED** [review]
ACK 61389dcba850a64f805a8b85afc927f964cfcec8

**Pull request merged**
