### PR TITLE
Fix a bunch of clippy lints

### PR DESCRIPTION
**Pull request by apoelstra**
Supercedes #615.

### CODE REVIEW

**Comment by tcharding** [comment]
Ha! linting like your a junior dev, thanks bro ... we need some junior devs around here.

**Review by tcharding — APPROVED** [review]
ACK 57eb924de0fd39286e468eb2249811ac45bd85c7

**Comment by tcharding** [comment]
If you were a junior dev I'd make you iterate on this one. Perhaps squash the whole thing into a single commit, you don't want all those commits in the index _for ever_ :)

(I'm still chuckling, the changes are all mixed up eg, random stuff in `into_iter` patch, `into_iter` changes in other patches.)

**Comment by tcharding** [comment]
The CI fail is legit, just got an unused import in there.

**Review by tcharding — APPROVED** [review]
ACK 7eccfdbee63bb3e97dd441fe0135e639667a829c

**Comment by apoelstra** [comment]
cc @sanket1729 I think we need your ACK here.

**Review by sanket1729 — APPROVED** [review]
ACK 7eccfdbee63bb3e97dd441fe0135e639667a829c

**Pull request merged**
