### PR TITLE
[backport] Several small fixes for 12.x

### PR DESCRIPTION
**Pull request by apoelstra**
We are incorrectly serializing and_n as "and_b", and incorrectly parsing `tr(<key>,)`.

In master the `and_b` thing is fixed by https://github.com/rust-bitcoin/rust-miniscript/pull/722 which rewrites the Display impl completely and the `tr(<key>,)` thing will be fixed as part of a coming series of PRs to clean up expression parsing.

Also includes #740 since it showed up in time.

### CODE REVIEW

**Review by sanket1729 — COMMENTED** [review]
ACK 98ea9df708a5fe538308a9e26881d03dfe21b76e

**Comment by apoelstra** [comment]
Actually I will hold off on this. Will add a patch for https://github.com/rust-bitcoin/rust-miniscript/issues/736 and anything else I find over the next few days.

**Comment by apoelstra** [comment]
Ready for review. I have fuzzed this against my rewritten code for 40 hours now without any new incompatibilities cropping up.

**Comment by apoelstra** [comment]
cc @sanket1729 oops, I totally forgot about this one. We should merge it too.

**Review by sanket1729 — APPROVED** [review]
ACK 9cedc49636c73268a7eba926cca9d7e37693752f

Oops. I just missed this in swarm of notifications :(

**Comment by apoelstra** [comment]
Tagged and published.

Will update my other PR to include a fuzztest against this.

**Pull request merged**
