### PR TITLE
Add serde impls for policies using macro

### PR DESCRIPTION
**Pull request by stevenroose**
Also changed the existing serde impls to use the macro.

### CODE REVIEW

**Comment by sanket1729** [comment]
Ack 05cf80d5c66e070776c7f79c4da88f4d08cdc06a. Travis complaining about `cargo fmt` failure.

**Comment by stevenroose** [comment]
Fixed.

**Comment by stevenroose** [comment]
Let me rebase.

**Comment by stevenroose** [comment]
Ok the extra type parameter on Miniscript was a bit of a pain. But I managed to do it :D

**Comment by sanket1729** [comment]
Neat. tACK 1b201945feda785d135b73bd7608725055826a6c

**Pull request merged**
