### PR TITLE
Small optimization of Tr descriptor parsing.

### PR DESCRIPTION
**Pull request by JeremyRubin**

### CODE REVIEW

**Comment by JeremyRubin** [comment]
probably not the right way to do this, but currently serializations using from_str will be broken otherwise.

**Comment by sanket1729** [comment]
This has been fixed in latest master, using something similar.

**Comment by JeremyRubin** [comment]
Ah I missed that one XD.

Just noticed it on an integration which was using a slightly stale revision.


I updated this PR to still be relevant, since in the version on master we end up checking for the ASCII + looking for the checksum twice. By directly calling Tr::from_str we save that extra pass.

I also made the match over 'tr(', since that captures that it is a function call v.s. any word starting with tr

**Review by sanket1729 — APPROVED** [review]
utACK 00e40e8fb469f0a951ba367cce75469fa3937089

**Pull request merged**
