### PR TITLE
Enable building docs in the CI pipeline

### PR DESCRIPTION
**Pull request by tcharding**
First fix all the docs build errors then enable docs build in CI, as we do in other crates in our stack.

### CODE REVIEW

**Review by apoelstra — DISMISSED** [review]
ACK 10339dc83a0cf3fbe2e5ca998c3a793fb7771952

Nice!

**Review by sanket1729 — APPROVED** [review]
ACK 10339dc83a0cf3fbe2e5ca998c3a793fb7771952

**Comment by sanket1729** [comment]
Would need rebase again

**Review by sanket1729 — APPROVED** [review]
re-ACK c40d350dde582ae84bc155c17a1aed37fe37722e

**Pull request merged**
