### PR TITLE
use a single-use temp name for integration test dir

### PR DESCRIPTION
**Pull request by z8674558**
Closes https://github.com/rust-bitcoin/rust-miniscript/issues/287

### CODE REVIEW

**Comment by apoelstra** [comment]
Can you use `xxd` rather than `base64` so we get hex-encoding? 10 digits is still more than enough.

As an aside, do we care about support for systems without `/dev/urandom` or anything like it? I guess not.

**Comment by z8674558** [comment]
> As an aside, do we care about support for systems without /dev/urandom or anything like it? I guess not.

Maybe it is better to use timestamp instead of random string, because what we want to do is to avoid conflict on the shared machine. We should be ok with just `date`

**Comment by z8674558** [comment]
updated to use `xxd`

**Comment by sanket1729** [comment]
Bitcoin core names it as `/tmp/bitcoin_func_test_o16z4jkv`. Anyways, I am okay with `xxd` or `base64`

**Review by sanket1729 — APPROVED** [review]
utACK e3dafb25284520a190ab50bc689b4eb76e15354a

**Comment by apoelstra** [comment]
utACK the current proposal (use `/dev/urandom` into `xxd`, add prefix)

**Review by apoelstra — APPROVED** [review]
ACK e3dafb25284520a190ab50bc689b4eb76e15354a

This looks great!

**Pull request merged**
