### PR TITLE
clippy: remove `.any(|x| x)` construction in the compiler

### PR DESCRIPTION
**Pull request by apoelstra**

### CODE REVIEW

**Review by apoelstra — COMMENTED** [review]
On d28b7ea2cff8285a21fa4e850dcbb600b2dfd356 successfully ran local tests

**Comment by sanket1729** [comment]
We can get this in with Tidwell's PR

**Review by sanket1729 — APPROVED** [review]
ACK d28b7ea2cff8285a21fa4e850dcbb600b2dfd356

**Comment by apoelstra** [comment]
Yep -- will merge as part of #766.

**Pull request closed without merging**
