### PR TITLE
Fix tr for each key bug

### PR DESCRIPTION
**Pull request by sanket1729**
You can re-order commits to see that this is fixed.

### CODE REVIEW

**Comment by sanket1729** [comment]
cc @dr-orlovsky

**Review by dr-orlovsky — APPROVED** [review]
tACK 92e504c6b55f7b5b0aa4db14dd8e9800b2639135

Tested with my wallet, now it works:

```yaml
xpub:
  tpubDC7mz8DJG7cy72MomPR2TmkfA6kjqYkEtYPHigBcycRaaPGD4fgmS8WWADEPNN685xVepi8nee1xGEYR33iNj9hy5HpqhtAKTT2uq4uq7jv:
    - 877c9433
    - "m/86'/1'/0'"
  tpubDC7mz8DJG7cyYEWffExngTpWvjn6rZqaAkugaiHKVzsw9jA5fL7Ch8G2KSxGpraZZNYEKaH4uDExLbtE5ySBA49ZZfP6aXjvAHVyyxjEEeu:
    - 877c9433
    - "m/86'/1'/10'"
  tpubDC7mz8DJG7cyb3BEFXtK1FbvoD3Y81RTjqUUvkaZDXbQExaaMAg1gNy1yLQeRYbL94eFfQ4WymxksrWJJYCLh7Fwrs1e5wG1TwAsKrruUS9:
    - 877c9433
    - "m/86'/1'/11'"
  tpubDC7mz8DJG7cycqGg8AnwnvRT2Gwwgr9tf6Xv8ejs6Ec5gcg1PPnukYnwUADsb6EQPT3SdHg6zrC9WRwoPUan2PpaqtNRbUJxWZJkGmeh1HZ:
    - 877c9433
    - "m/86'/1'/12'"
```

Previosly it was just two keys, not four)

**Comment by dr-orlovsky** [comment]
May I ask please to do RC2 after the fix merge?

**Comment by sanket1729** [comment]
I think we want to do another RC after next RC for rust-bitcoin

**Review by apoelstra — APPROVED** [review]
ACK 92e504c6b55f7b5b0aa4db14dd8e9800b2639135

**Pull request merged**
