### PR TITLE
add tests for script deserialization

### PR DESCRIPTION
**Pull request by joemphilips**
While I was trying to [port this library into C#](https://github.com/MetacoSA/NBitcoin/pull/764) , I found a bug in script deserialization.

I was trying to fix it by myself, but I'm afraid that the spec will change again. So I will not do it for now (unless we are sure that the spec won't change drastically anymore.)

Here is the failing case, tell me if I'm doing something wrong.

### CODE REVIEW

**Comment by apoelstra** [comment]
Thanks for this report - sorry for letting it drop. I will try to investigate today.

**Comment by apoelstra** [comment]
offending script:
`OP_IF OP_SIZE OP_PUSHBYTES_1 20 OP_EQUALVERIFY OP_HASH256 OP_PUSHBYTES_32 131772552c01444cd81360818376a040b7c3b2b7b0a53550ee3edde216cec61b OP_EQUAL OP_ELSE OP_0 OP_ENDIF OP_VERIFY OP_SIZE OP_PUSHBYTES_1 20 OP_EQUALVERIFY OP_SHA256 OP_PUSHBYTES_32 ec4916dd28fc4c10d78e287ca5d9cc51ee1ae73cbfde08c6b37324cbfaac8bc5 OP_EQUALVERIFY OP_PUSHNUM_1`

or `6382012088aa20131772552c01444cd81360818376a040b7c3b2b7b0a53550ee3edde216cec61b876700686982012088a820ec4916dd28fc4c10d78e287ca5d9cc51ee1ae73cbfde08c6b37324cbfaac8bc58851`

**Comment by apoelstra** [comment]
Yep, I see ... the problem is that when we are parsing backward after seeing `VERIFY`, we parse `OP_EQUAL` and think we're in a pubkeyhash construction, but we're actually in a hashlock construction. We need to split up `Terminal::PkH` into a `NonTerminal::PkHOrHashLock` so that we can differentiate these cases.

Great find!

**Comment by apoelstra** [comment]
This PR needs an update to rename `c:pk` to `pk`, `thresh_m` to `multi`, and to use `Segwitv0Script` rather than `Miniscript::<bitcoin::PublicKey>`.

It still does not pass by the way, even with these fixes.

**Comment by sanket1729** [comment]
@apoelstra This test has been included in the #78  and this can be closed.

**Pull request closed without merging**
