### PR TITLE
policy: fix semantic lifting from andor

### PR DESCRIPTION
**Pull request by darosior**
Y and Z were mixed up

### CODE REVIEW

**Comment by sanket1729** [comment]
`rustfmt` failure, and looks like our earlier tests were broken

**Comment by darosior** [comment]
Fixed `rustfmt` and 1.29 compilation

**Comment by darosior** [comment]
Fixed the HTLC example, which asserted the wrong behaviour.

**Review by sanket1729 — APPROVED** [review]
ACK 73047923b05a368cbfb36f75f515e5a1574b094c

**Pull request merged**
