### PR TITLE
lib: implement PartialEq for miniscript::Error

### PR DESCRIPTION
**Pull request by darosior**
This helps a lot downstream, and we can do that now that rust-bitcoin derives `PartialEq` everywhere.

### CODE REVIEW

**Comment by tcharding** [comment]
We need to derive `PartialEq` on `miniscript::analyzable::AnalysisError` as well then this should pass CI.

**Comment by darosior** [comment]
Oh, i had forgotten about this, sorry. Should be good now.

**Review by tcharding — APPROVED** [review]
ACK 1356f039a712cf7b9590453b5010218c68153257

**Review by sanket1729 — APPROVED** [review]
ACK 1356f039a712cf7b9590453b5010218c68153257

**Pull request merged**
