### PR TITLE
Implement `source` for error types

### PR DESCRIPTION
**Pull request by tcharding**
Now we have MSRV of 1.41.1 we can implement `source` for improved error handling.

Patches 1-3 are preparatory cleanup, patch 4 adds all the `source` impls.

Resolves: #273

### CODE REVIEW

**Review by apoelstra — DISMISSED** [review]
ACK 013922ceb0fdb576e40ff91908734ed64786d3f2

I did not check that this exhaustively implements `Error` everywhere that it can/should be.

**Comment by tcharding** [comment]
Face palm, I did this same work in [`rust-bitcoin` ](https://github.com/rust-bitcoin/rust-bitcoin/pull/987)and `rust-miniscript` but I did two things differently in each
- In one I use fully quallified path `std::error::Error` and in one I import `std::error`.
- In one I put `source` above `Display` and in the other I put it below.

My OCD cannot handle that so I'll fix them both tomorrow, sending this to draft. Please comment if you have an opinion on these otherwise I'll arbitrarily pick and do them all the same.

**Comment by apoelstra** [comment]
No opinion :).

**Review by apoelstra — APPROVED** [review]
ACK 5935d867d9eb26dbac979d66b1579933e043986d

**Review by sanket1729 — APPROVED** [review]
ACK 5935d867d9eb26dbac979d66b1579933e043986d. Checked that all changes correctly pass through the source. Did not check whether there are more Error types that are not covered.

**Pull request merged**
