### PR TITLE
fuzz: add target for `Descriptor::parse_descriptor`

### PR DESCRIPTION
**Pull request by brunoerg**

### CODE REVIEW

**Comment by apoelstra** [comment]
Looks like CI is failing because of clippy:

```
  --> fuzz/fuzz_targets/parse_descriptor_priv.rs:11:57
   |
11 |     if let Ok((desc, _)) = Descriptor::parse_descriptor(&secp, &data_str) {
   |                                                         ^^^^^ help: change this to: `secp`
   |
```

**Comment by brunoerg** [comment]
@apoelstra thanks, fixed!

**Review by sanket1729 — APPROVED** [review]
ACK eb1e9f63387045fe8e8d9bac2dad9708eba948be

**Review by apoelstra — APPROVED** [review]
ACK eb1e9f63387045fe8e8d9bac2dad9708eba948be; successfully ran local tests; thanks!

**Pull request merged**
