### PR TITLE
Release 9.0.0

### LINKED ISSUE #483: We should not be running pkh logic through rawpkh
See for example https://github.com/rust-bitcoin/rust-miniscript/blob/master/src/miniscript/satisfy.rs#L937 (not sure if there are any other examples). Here we have a public key, convert it to a hash, then look up the key again from that.

In #481 (the "planning module" PR) I am suggesting that we work with `DescriptorPublicKey`s rather than `DefinitePublicKey`s, which means that we may be working with keys where we don't know their hash160 and can't do this lookup. So in addition to being unnecessary, this roundtrip through a hash may become wrong.

### PR DESCRIPTION
**Pull request by sanket1729**
- Cleanup some pkh code in satisfaction
- Fixes #483
- Fixes another bug dealing with dissatisfaction of thresh inside pkh
- Adds example test vector from discussions
- release 9.0.0 with above fixes

### CODE REVIEW

**Comment by apoelstra** [comment]
I'm not sure that we can change the `Display` output in a patch release.

**Comment by apoelstra** [comment]
Changing the signature of `Satisfier::lookup_raw_pkh_pk` we definitely *can't* do in a patch release.

**Comment by apoelstra** [comment]
All changes in 7e1a7a098baf324a628cc426da4442a8599e6d92 look good to me, but they're all API-breaking and I think we need to release 9.0.0 with them.

**Comment by sanket1729** [comment]
All of the changes are related to the raw APIs. I was thinking we can just
justify them as a bug fix instead of major release?

Thinking from a software sense, it makes sense to call it a breaking
change.

**Comment by engenegr** [comment]
@apoelstra what is expected date for the next release if the fix goes with it?

**Comment by sanket1729** [comment]
@engenegr, you can expect a new release early next week.

**Comment by sanket1729** [comment]
Changed to release 9.0.0

**Comment by apoelstra** [comment]
@sanket1729 you did not change the actual commit to 9.0.0!

**Comment by sanket1729** [comment]
@apoelstra , lol. Good catch

**Review by apoelstra — APPROVED** [review]
ACK a113e35923dc094b2554209d2042ac8d7683ebb7

**Comment by apoelstra** [comment]
Tagged & published

**Pull request merged**
