### PR TITLE
Add timelock mix tests from miniscript alloy spec

### PR DESCRIPTION
**Pull request by sanket1729**
There found one bug in the current type system! The last commit disables the test while I work on fuzzer fix for rust-secp256k1.

### CODE REVIEW

**Comment by apoelstra** [comment]
Can you rebase this? Github is confused and is still showing two commits from #257 in this.

**Comment by sanket1729** [comment]
Rebased

**Comment by sanket1729** [comment]
But this still has bugs, I am yet to address the changes to fuzz tests and removing the `#[cfg(not(fuzzing))]` thing

**Comment by apoelstra** [comment]
Do these tests need to be ignored? On my system they run in less than a second.

**Comment by sanket1729** [comment]
No, these run really fast. I don't think the ignored is needed.

**Review by apoelstra — APPROVED** [review]
ACK 003226ee34cd13048eda165404bddda644a736be

**Pull request merged**
