### PR TITLE
Tracking PR for release `v11.0.0`

### PR DESCRIPTION
**Pull request by tcharding**
Release time yo!

Close: #622

### CODE REVIEW

**Comment by tcharding** [comment]
@apoelstra I only check recent-ish PS that are mergable, are there any others we need/want?

**Comment by apoelstra** [comment]
cc @sanket1729

I think all we need is the bitcoin update.

**Comment by apoelstra** [comment]
Super cool to get the planning module into a release!

**Review by apoelstra — APPROVED** [review]
ACK e6212ab55943ffd04cc4b1cf0ee23cabb7f79a47

**Comment by apoelstra** [comment]
Tagged and published.

**Pull request merged**
