### PR TITLE
Reduce line count

### PR DESCRIPTION
**Pull request by tcharding**
This PR is formatting changes only, totally non-urgent.

Reduce line count by setting a couple of rustfmt config options to be the same as they are in `rust-bitcoin`. Final patch removes whitespace in trait impl blocks, and was the impetus for this PR.

### CODE REVIEW

**Comment by apoelstra** [comment]
I think increasing `chain_width` is mostly a bad change.

**Comment by apoelstra** [comment]
But 0c7a972bc3693f7cc0a6fed108ad11f2b8afdbb6 looks good otherwise.

**Comment by tcharding** [comment]
So, assuming the comment I wrote in the rustfmt config file of rust-bitcoin is correct, we can't keep `chain_width` with a custom setting and not all the others if we want to use `use_small_heuristics = "Max"` - is the chain width annoying enough to warrant dropping this whole patch? Real question, this is your and @sanket1729's call, I'm jonny come lately to this crate.

**Comment by tcharding** [comment]
I split each config option change into a separate patch so they can be viewed easily. I actually think the only massive win is `fn_single_line` and maybe `struct_lit_width`.

**Comment by tcharding** [comment]
FTR docs say the values are a percentage of `max_width` but anything over 80 causes an error, so there is a bug somewhere.

`fn_call_width` cannot have a value that exceeds `max_width`. `fn_call_width` will be set to the same value as `max_width`

**Comment by tcharding** [comment]
> Not really a fan of the array_width change either.

No worries, I'll drop that commit - that is exactly why I kept them all separate :)

**Comment by tcharding** [comment]
Force push removes the `array_width` change (was the last patch of the series).

**Comment by tcharding** [comment]
> Otherwise https://github.com/rust-bitcoin/rust-miniscript/commit/75d3fa8da07c4ae62f6194c3078f529c924f479b looks good.

This is the commit hash of the removed patch.

**Review by apoelstra — APPROVED** [review]
ACK 1cab0b872854a00bc7bfb2dc52a47a81350240fc

**Comment by tcharding** [comment]
Rebased, no other changes.

**Review by apoelstra — DISMISSED** [review]
ACK f41a70db0f403ac047b0e76f6585c05854bfaa60

**Comment by tcharding** [comment]
Re-done after `planning` module merging. @TheBlueMatt this one should make you all warm and fuzzy inside :)

**Comment by sanket1729** [comment]
@tcharding, what order do you prefer I merge the PRs?

**Review by apoelstra — APPROVED** [review]
ACK 26bb52e2037a9d603264943770e7f5c31be7bddd

**Comment by tcharding** [comment]
This one first please, it will cause loads of conflicts but that is always going to be the case whenever it merges.

**Pull request merged**
