### PR TITLE
Update rustfmt.toml

### PR DESCRIPTION
**Pull request by tcharding**
It seems like we are getting closer to being able to introduce `rustfmt` in `rust-bitcoin`.

Update the `rustfmt` configuration file to be the same (except for excludes) as the proposed config in `rust-bitcoin`.

Raising as draft because there isn't much point merging this until https://github.com/rust-bitcoin/rust-bitcoin/pull/1040 is finialized.

@sanket1729 can I be a pain and ask you to flick through this some time please? Perhaps, to make it less painful, you could just give either a 'soft yes' or a 'hard no'? Thanks man.

### CODE REVIEW

**Comment by tcharding** [comment]
The `required_version` field is a bit of a pain. It will fail on PRs any time the rustfmt team drops a release.

**Comment by tcharding** [comment]
No comments on this, closing.

**Comment by sanket1729** [comment]
Sorry man. I feel bad seeing all these PRs closed for inactivity from my side. I will make a point to put one day per week at least for rust-bitcoin ecosystem.

**Comment by tcharding** [comment]
No stress man, I've been slack and not put enough work into rust-miniscript also. This closing was more a reflection of that than of anything your side.

**Pull request closed without merging**
