### PR TITLE
Clarify that alloy tests don't actually test timelock mixing

### PR DESCRIPTION
**Pull request by sanket1729**

### CODE REVIEW

**Comment by sanket1729** [comment]
MSRV is also breaking, so added a CI fix to this commit.

**Review by tcharding — APPROVED** [review]
ACK e94efbfa3d270eb3a4d6cf19a94998e1f8053cad

**Comment by sanket1729** [comment]
@apoelstra, can you take a look at this quick PR? Should fix the CI here.

**Comment by apoelstra** [comment]
Looks good. Running tests now, assuming it succeeds you should see an ACK within the hour.

**Review by apoelstra — APPROVED** [review]
ACK e94efbfa3d270eb3a4d6cf19a94998e1f8053cad

**Pull request merged**
